version: "3.9"
services:
  db:
    image: mongo:4.4
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - ${MONGODB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
      MONGO_INITDB_DATABASE: ${MONGODB_NAME}